# Use Node.js v20.13.1 as the base image
FROM node:20.13.1-alpine

# Set working directory inside the container
WORKDIR /admin

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port Strapi is running on
EXPOSE 1337

# Command to run the application
CMD ["npm", "start"]
