"use client"
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";

import { Toaster } from "@/components/ui/sonner";
import { UpdateCartContext } from "./_context/UpdateCartContex";
import {  useState } from "react";
//import { usePathname } from "next/navigation";


const outfit = Outfit({ subsets: ["latin"] });


//export const metadata: Metadata = {
 // title: "Grocery-store",
//  description: "Generated by create next app",
//};



// Create the context with the custom context type


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Use useState to manage the state for updateCart
  const [updateCart, setUpdateCart] = useState<boolean>(false);
 
  return (
    <html lang="en">
      <body className={outfit.className}>
        {/* Provide the context value to the children */}
        <UpdateCartContext.Provider value={{ updateCart, setUpdateCart } as any}>
          {children}
        </UpdateCartContext.Provider>
        <Toaster />
       
      </body>
    </html>
  );
}